name: LoginSecurity
version: '${project.version}'
main: com.izakdvlpr.loginsecurity.LoginSecurityMain
author: izakdvlpr
commands:
  login:
    aliases: ["logar"]
  register:
    aliases: ["registrar"]
