name: ZKSecurity
version: '${project.version}'
main: com.izakdvlpr.security.ZKSecurityMain
author: izakdvlpr
depend: [TitleAPI]
commands:
  login:
    aliases: ["logar"]
  register:
    aliases: ["registrar"]
  email:
    aliases: ["mail"]
  verify:
    aliases: ["verificar"]
