name: LoginSecurity
version: '${project.version}'
main: com.izakdvlpr.loginsecurity.LoginSecurityMain
author: izakdvlpr
depend: [TitleAPI]
commands:
  login:
    aliases: ["logar"]
  register:
    aliases: ["registrar"]
